# -*- coding: utf-8 -*-
"""Solucion_Quijote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-AcAJj4yTCu7x1uywyE7iGt3CxgqlYI
"""

f = open("quijote.txt", "r", encoding = "utf-8")
mensaje = f.read()
print(mensaje)

from collections import Counter
import re



num_palabras = len(mensaje)
num_caracteres = len(mensaje)
num_oraciones = len(mensaje)


print("Cantidad de palabras: ", num_palabras)
print("Cantidad de caracteres: ", num_caracteres)
print("Cantidad de oraciones: ", num_oraciones)


def obtener_frecuencia_palabras(texto):
    # Convertir todo a minúsculas para evitar diferencias en mayúsculas/minúsculas
    texto = texto.lower()

    # Eliminar caracteres no alfabéticos, como puntuación y números
    texto_limpio = re.sub(r'/content/quijote.txt', ' ', texto)

    # Dividir el texto en palabras
    palabras = texto_limpio.split()

    # Contar la frecuencia de cada palabra
    contador_palabras = Counter(palabras)

    return contador_palabras

# Ejemplo de uso
texto_ejemplo = mensaje
frecuencia_palabras = obtener_frecuencia_palabras(mensaje)
print(frecuencia_palabras)

